name: inkostel
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+2
  intl: 0.19.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  carousel_slider: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  awesome_notifications: ^0.9.3+1
  get: ^4.6.6
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  geolocator: ^7.7.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  random_string: ^2.3.1
  fluttertoast: ^8.2.5
  path_provider: ^2.1.3
  firebase_storage: ^11.7.4
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  assets:
    - images/hapid.jpg
    - images/contoh.jpg
    - images/kamar.png
    - lib/icons/
    - images/gambar.png
    - images/profile.png
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
